//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tset2
{
    using System;
    using System.Collections.Generic;
    
    public partial class files
    {
        public long id { get; set; }
        public byte[] file { get; set; }
        public long user_id { get; set; }
        public string name { get; set; }
    
        public virtual user user { get; set; }
    }
}
